extends:
  - "plugin:@typescript-eslint/recommended"
  - "eslint:recommended"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
  - "plugin:react/recommended"

plugins:
  - "@typescript-eslint"

env: 
  browser: true
  es6: true
  jest: true

parser: "@typescript-eslint/parser"


rules:
  prettier/prettier: "error"

settings:
  react:
    version: 'detect'

ignorePatterns:
  - '**/*.svg'
  - '**/*.scss'
  - '**/*.css'
